CREATE VIEW TeamGame2016_View AS SELECT Teams.Name AS Name, 
TeamGame.TeamID AS TeamID,
TeamGame.GameID AS GameID, 
Games2016_View.Date AS Date, 
Games2016_View.Week AS Week, 
Games2016_View.Day AS Day, 
Games2016_View.Time AS Time, 
CASE WHEN (Name LIKE Games2016_View.Winner) THEN 'Y' ELSE 'N' END AS Won, 
CASE WHEN (Name LIKE Games2016_View.Winner) THEN Games2016_View.Loser ELSE Games2016_View.Winner END AS Opponent, 
CASE WHEN (Name LIKE Games2016_View.Winner) THEN Games2016_View.WinScore ELSE Games2016_View.LoseScore END AS TotalScore, 
CASE WHEN (Name LIKE Games2016_View.Winner) THEN Games2016_View.LoseScore ELSE Games2016_View.WinScore END AS OppScore, 
Games2016_View.Duration AS Duration, 
Games2016_View.Stadium AS Stadium, 
CASE WHEN Stadium IN (SELECT DISTINCT Stadiums.Name FROM Stadiums, TeamHomeStadium, Teams WHERE TeamHomeStadium.StadiumID = Stadiums.StadiumID AND TeamHomeStadium.TeamID = Teams.TeamID AND Teams.TeamID = TeamGame.TeamID) THEN 'Y' ELSE 'N' END AS Home, 
Games2016_View.Roof AS Roof, 
Games2016_View.Surface AS Surface, 
Games2016_View.Temp AS Temp, 
Games2016_View.Humidity AS Humidity, 
Games2016_View.Wind AS Wind, 
TeamGame.1stDowns AS 1stDowns, 
TeamGame.RushAtt AS RushAtt, 
TeamGame.RushYds AS RushYds, 
TeamGame.RushTds AS RushTds, 
TeamGame.PassComp AS PassComp, 
TeamGame.PassAtt AS PassAtt, 
TeamGame.PassYds AS PassYds, 
TeamGame.PassTds AS PassTds, 
TeamGame.Ints AS Ints, 
TeamGame.Sacked AS SkTaken, 
TeamGame.SackedYds AS SkYds, 
TeamGame.NetPassYds AS NetPassYds, 
TeamGame.TotalYds AS TotalYds, 
TeamGame.Fumbles AS Fmb, 
TeamGame.FumblesLost AS FL, 
TeamGame.Turnovers AS Turnovers, 
TeamGame.Penalties AS Pen, 
TeamGame.PenaltyYds AS PenYds, 
TeamGame.3rdM AS 3rdM, 
TeamGame.3rdAtt AS 3rdAtt, 
TeamGame.4thM AS 4thM, 
TeamGame.4thAtt AS 4thAtt, 
TeamGame.TOP AS TOP, 
TeamGame.Q1 AS Q1, 
TeamGame.Q2 AS Q2, 
TeamGame.Q3 AS Q3, 
TeamGame.Q4 AS Q4, 
TeamGame.OT AS OT, 
TeamGame.URL AS URL 
FROM (Teams, TeamGame) 
LEFT JOIN Games2016_View ON Games2016_View.GameID = TeamGame.GameID 
WHERE TeamGame.TeamID = Teams.TeamID
AND Games2016_View.Date BETWEEN '2016-04-20' AND '2017-04-20'
